### ISSUE TITLE
bug: Signing txs in zombienet tests

### ISSUE THREAD

**Issue by chiefbiiko** [t3rn/t3rn#602]
Cannot sign and send transactions in zombienet's feature javascript testing.

## Expected behavior

Signing and sending transaction should work just fine when zombienet testing.

### Actual behavior

```js
await tx.signAndSend(signer)
```

fails with

`Cannot read properties of undefined (reading 'isEmpty')`.

### Steps to reproduce

Consider a setup of:

`Makefile`

```yml
...
test-asset-tx-payment:
	$(bin_dir)/zombienet --provider=$(provider) test ./0001-asset-tx-payment.feature
...
```

`0001-asset-tx-payment.feature`

```yml
Description: Asset Transaction Payments
Network: ./zombienet.toml
Creds: config

alice: is up
bob: is up
alice: parachain 3000 is registered within 10 seconds
t0rn-collator01: js-script ./asset_tx_payment.js within 60 seconds
```

`asset_tx_payment.js`

```js
async function run(nodeName, networkInfo, args) {
  await zombie.util.cryptoWaitReady()

  let { wsUri, userDefinedTypes } = networkInfo.nodesByName[nodeName]
  let api = await zombie.connect(wsUri, userDefinedTypes)

  let keyring = new zombie.Keyring({ type: "sr25519" })
  let alice = keyring.addFromUri("//Alice")
  let bob = keyring.addFromUri("//Bob")

  // force_create and set_metadata an asset
  let name = "Asset"
  let symbol = "ASS"
  let decimals = 12
  let id = 1n
  let owner = alice.address
  let isSufficient = true
  let minBalance = 1n

  await api.tx.sudo
    .sudo(api.tx.assets.forceCreate(id, owner, isSufficient, minBalance))
    .signAndSend(alice)
  await api.tx.sudo
    .sudo(api.tx.assets.setMetadata(id, name, symbol, decimals))
    .signAndSend(alice)

  // mint some asset balance to bob

  // have bob do a tx paying with the non-native asset
}

module.exports = { run }
```

Running `make test-asset-tx-payment` should reproduce the error.

### Screenshot

![zstxs](https://user-images.githubusercontent.com/22937570/214827656-4cc1ae2d-79ef-4f1b-b5da-e5bc6d4e67ad.png)
